### ISSUE TITLE
Gamepad not working under WINE

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#283]
Game version 1.03, emulated via wine(q4wine)

**Comment by omagadsamsa** [comment]
I just tested the crash nitro kart and it doesn't work either

**Comment by ciciplusplus** [comment]
Steam deck is not an "officially" supported platform for us. Nor running a Windows build under the Wine.

**Comment by omagadsamsa** [comment]
I was able to get this to work via proton 9.0 beta

**Comment by hikari-no-yume** [comment]
I actually tried Super Monkey Ball in WINE yesterday, on Ubuntu 22.04. Interestingly it detected my Xbox One controller (shows up in the logs) but it didn't work.

As @ciciplusplus said, WINE isn't a supported platform for us, but I'm going to reopen this anyway because it's an interesting issue to keep track of. There's a chance updating our SDL2 version might fix it, not sure.

**Comment by omagadsamsa** [comment]
It seems to me that this is so, multi-touch doesn’t work for me yet

> I actually tried Super Monkey Ball in WINE yesterday, on Ubuntu 22.04. Interestingly it detected my Xbox One controller (shows up in the logs) but it didn't work.
> 
> As @ciciplusplus said, WINE isn't a supported platform for us, but I'm going to reopen this anyway because it's an interesting issue to keep track of. There's a chance updating our SDL2 version might fix it, not sure.

**Comment by corped12** [comment]
I tried using my Switch joycons under wine on raspberry pi os (debian 12) and it worked

**Comment by nighto** [comment]
I was able to use touchHLE with game controls on a Steam Deck running with Proton, so I believe this issue could be closed.

**Comment by hikari-no-yume** [comment]
Yeah I guess it's an issue with some older WINE version, I'll close it.
