### ISSUE TITLE
Authentication error in “a-yo sushi”

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#301]
The thing is that I found a working game a-yo sushi, but its virginity time has expired and does not allow me to go beyond this screen to the game

**Comment by hikari-no-yume** [comment]
Its what?

**Comment by omagadsamsa** [comment]
> Its what?

![Screenshot_20240509-232954](https://github.com/touchHLE/touchHLE/assets/149837198/ce9e57e9-7bdb-40da-bfed-a44c337f49ee)

**Comment by hikari-no-yume** [comment]
Have you tested that changing the time on your computer actually fixes the game?

**Comment by omagadsamsa** [comment]
> Have you tested that changing the time on your computer actually fixes the game?

I'll try to do this right now

**Comment by omagadsamsa** [comment]
> > Have you tested that changing the time on your computer actually fixes the game?
> 
> I'll try to do this right now

same error, problem in the app

**Comment by hikari-no-yume** [comment]
Then the time is not the problem.

The Korean text means “authentication error”. Most likely the problem is that touchHLE does not support HTTP requests currently. However, as this is an old app, it is unlikely the servers it relies on are still online, so it would presumably fail even if touchHLE did support HTTP requests. So I don't think there's much we can do.
